version: '3.3'

networks:
  example-net:
    external:
      name: example-network

services:

  tornado_server:
    build: .
    command: python3 run_server.py
    volumes:
      - .:/usr/src
    ports:
      - "9000:9000"
    networks:
      - example-net

  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"
    networks:
      - example-net

  celery_server:
    build: .
    command: celery -A celery_app.celery worker -l info
    volumes:
      - .:/usr/src
    depends_on:
      - redis
    networks:
      - example-net